version: "3.9"
services:
  mongo:
    image: mongo:4.2.5
    ports:
      - "27017:27017"

#  nginx:
#    build: ./nginx
#    ports:
#      - "80:80"
#      - "443:443"

  web:
    build: .
    environment:
      "SERVER_PORT": 23315
      WAIT_HOSTS: mongo:27017
      DB: mongo:27017
    ports:
      - "23315:23315"
